DROP TABLE demo_user

CREATE TABLE demo_user(
id INT(11) NOT NULL AUTO_INCREMENT,
NAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

SELECT * FROM demo_user;
INSERT INTO demo_user(NAME,PASSWORD) VALUES('22222', '123456')

INSERT INTO demo_user(NAME, PASSWORD) VALUE('谢高扬', '12345');

 INSERT INTO demo_user(NAME, PASSWORD) VALUE( '石超熊', '12345' ) ; INSERT INTO demo_user(NAME, PASSWORD) VALUE( '余静', '123456' );

